# Generated by Django 5.1.7 on 2025-06-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_email_alter_user_passage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('idade', models.PositiveIntegerField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('objetivo', models.CharField(choices=[('hipertrofia', 'Hipertrofia'), ('emagrecimento', 'Emagrecimento'), ('definicao', 'Definição')], max_length=20)),
                ('nivelatv', models.CharField(choices=[('sedentário', 'Sedentário'), ('leve', 'Leve'), ('moderado', 'Moderado'), ('intenso', 'Intenso'), ('atleta', 'Atleta')], max_length=20)),
                ('alimentacao', models.CharField(choices=[('vegano', 'Vegano'), ('vegetariano', 'Vegetariano'), ('sem gluten', 'Sem Gluten'), ('sem lactose', 'Sem Lactose'), ('sem restrições', 'Sem Restrições')], max_length=20)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
    ]
