# Generated by Django 5.1.7 on 2025-06-14 01:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cadastro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cadastro',
        ),
        migrations.AddField(
            model_name='user',
            name='alimentacao',
            field=models.CharField(choices=[('vegano', 'Vegano'), ('vegetariano', 'Vegetariano'), ('sem gluten', 'Sem Gluten'), ('sem lactose', 'Sem Lactose'), ('sem restrições', 'Sem Restrições')], default='sem restrições', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='altura',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='user',
            name='idade',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='user',
            name='nivelatv',
            field=models.CharField(choices=[('sedentário', 'Sedentário'), ('leve', 'Leve'), ('moderado', 'Moderado'), ('intenso', 'Intenso'), ('atleta', 'Atleta')], default='leve', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='objetivo',
            field=models.CharField(choices=[('hipertrofia', 'Hipertrofia'), ('emagrecimento', 'Emagrecimento'), ('definicao', 'Definição')], default='definição', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='peso',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='user',
            name='senha',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
